schema update changes
Airstack-xyz/Subgraphs pull request #30
Opened 2023-01-09 10:01 UTC by anshulforyou

2023-01-09 17:46 UTC, 0xsarvesh requested changes

2023-01-09 17:46 UTC, 0xsarvesh commented on airstack-modules/modules/airstack/utils.ts
> +    return network.trim().toUpperCase().replace("-", "_");
Instead of this create a mapping.

2023-01-10 09:02 UTC, anshulforyou commented on airstack-modules/src/integrate.ts
> +  fileContent += `\nexport const SUBGRAPH_NAME = "${SUBGRAPH_NAME}";\nexport const SUBGRAPH_SLUG = "${SUBGRAPH_SLUG}";\n`
No, it's an improvement. SUBGRAPH_NAME and SLUG will now be added to new line, previously they were being added to the last line

2023-01-11 06:50 UTC, 0xsarvesh submitted a review, later dismissed

2023-01-11 06:55 UTC, 0xsarvesh commented on airstack-modules/graphql/airstack-nft-marketplace-schema.graphql.ts
> +  hash: String! #todo: Check if this should be bytes
Can you remove this comments.

2023-01-11 07:03 UTC, anshulforyou commented on airstack-modules/graphql/airstack-nft-marketplace-schema.graphql.ts
> +  hash: String! #todo: Check if this should be bytes
Done

2023-01-11 07:09 UTC, 0xsarvesh approved these changes

2023-01-11 07:09 UTC, merged