seaport royalty zero fix
Airstack-xyz/Subgraphs pull request #32
Opened 2023-01-12 12:17 UTC by anshulforyou

2023-02-09 14:09 UTC, rahul7668gupta commented
LGTM

2023-02-09 14:10 UTC, rahul7668gupta submitted a review, later dismissed

2023-02-15 15:09 UTC, 0xsarvesh requested changes

2023-02-15 15:09 UTC, 0xsarvesh commented on seaport-subgraph/src/seaport.ts
> +      if (royaltyBeneficiary == Address.zero() && royaltyFees.div(BigInt.fromI64(allSales.length)) != BIGINT_ZERO) {
You can just check `royaltyFees  !=  BIGINT_ZERO`  ?

2023-02-15 17:39 UTC, 0xsarvesh approved these changes

2023-02-15 17:40 UTC, 0xsarvesh approved these changes

2023-02-15 17:40 UTC, merged