Airstack module update for Domain Name vertical
Airstack-xyz/Subgraphs pull request #35
Opened 2023-01-25 13:17 UTC by rahul7668gupta

This PR:
1. adds domain name vertical for the airstack module
2. makes copying modules files vertical specific
3. removes redundant code from the module

2023-01-25 15:01 UTC, deepesh-kn requested changes
Few changes are in other PR, please fix this, will merge and do a review again.

```
abis/Airstack.json
abis/ERC20.json
```
May be needed. Please confirm if its working fine after deleting.

Also lets revisit the type `Bytes` used in the schema, should that be of type `string`?

2023-01-25 15:39 UTC, rahul7668gupta commented on airstack-modules/bin/index.ts
> +            transactionHash: Bytes,
this is a param to track function, while storing in db, its being converted to string

2023-01-25 15:41 UTC, rahul7668gupta commented on airstack-modules/package.json
> +    "build": "npm run build:package && npm pack"
this will require schema.graphql and subgraph.yaml files to be there, but package build without this line works fine!

2023-01-25 15:45 UTC, rahul7668gupta commented on airstack-modules/src/integrate.ts
> +function copyDomainNameModules(): string {
fixed

2023-01-25 15:53 UTC, rahul7668gupta commented
> Few changes are in other PR, please fix this, will merge and do a review again.
> 
> ```
> abis/Airstack.json
> abis/ERC20.json
> ```
> 
> May be needed. Please confirm if its working fine after deleting.
> 
> Also lets revisit the type `Bytes` used in the schema, should that be of type `string`?

1. yes, even after removing the Abis folder, npm run build works, also, even before deleting, Abis were not getting copied.
2. txn hash in being taken in bytes but being converted to string inside the module.

steps to build module:
1. switch to `airstack-modules` dir
2. `npm run build`

2023-01-25 16:00 UTC, rahul7668gupta commented
@deepesh-kn I have addressed the comments, please re-review and merge.

2023-01-27 07:47 UTC, deepesh-kn commented on airstack-modules/bin/index.ts
> +            transactionHash: Bytes,
Lets make it as string.

2023-01-27 07:54 UTC, deepesh-kn commented
Merging this to the feature branch, because the feature branch is not yet reviewed. The entire code will be reviewed in the feature branch.

2023-01-27 07:54 UTC, merged