Lens v2 profile subgraph changes
Airstack-xyz/Subgraphs pull request #88
Opened 2023-10-17 04:19 UTC by 0xsarvesh

- Added logic for subgraph to handle lens profile, handles, handle link, unlink & transfer
- Require module installation 

```
npx  @airstack/subgraph-generator social

```
name - lens_v2
version - 2.0.0
slug - lens_v2_polygon

2023-10-17 16:39 UTC, 0xsarvesh commented on lens_v2/package.json
> +    "@airstack/subgraph-generator": "file:../airstack-modules/airstack-subgraph-generator-1.0.0-alpha.3.tgz",
I am working to get module changes published. Once its published, can change to npm

2023-10-17 17:09 UTC, sharathkrml requested changes

2023-10-18 03:55 UTC, 0xsarvesh commented on lens_v2/src/lens-handle.ts
> +      LENSHANDLE_ADDRESS.toHexString(),
Did it whereever it was possible

2023-10-18 03:55 UTC, 0xsarvesh commented on lens_v2/src/lens-handle.ts
> +
Removed

2023-10-18 14:59 UTC, Hrishikesh-Thakkar commented on lens_v2/package-lock.json
Should we commit this?

2023-10-18 15:25 UTC, sharathkrml commented on lens_v2/src/lens-handle.ts
> +      LENSHANDLE_ADDRESS.toHexString(),
ok

2023-10-19 13:21 UTC, merged